# Generated by Django 4.2.25 on 2025-10-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('pickup', 'รับสินค้า'), ('delivery', 'จัดส่ง')], max_length=10, verbose_name='ประเภทบริการ')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'เวลาทำการ',
                'verbose_name_plural': 'เวลาทำการ',
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลามอบหมาย')),
                ('status', models.CharField(choices=[('assigned', 'ได้รับมอบหมาย'), ('accepted', 'รับงาน'), ('picked_up', 'รับสินค้าแล้ว'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='assigned', max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='คนขับ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='orders.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'การมอบหมายงานจัดส่ง',
                'verbose_name_plural': 'การมอบหมายงานจัดส่ง',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาจัดส่งที่คาดการณ์')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาจัดส่งจริง')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='คนจัดส่ง')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='orders.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'การจัดส่ง',
                'verbose_name_plural': 'การจัดส่ง',
            },
        ),
    ]
