# Generated by Django 4.2.25 on 2025-10-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('pickup', 'รับเองที่ร้าน'), ('delivery', 'จัดส่ง')], max_length=10, verbose_name='ประเภทคำสั่งซื้อ')),
                ('payment_method', models.CharField(choices=[('line_pay', 'LINE Pay'), ('promptpay', 'PromptPay'), ('truemoney', 'TrueMoney Wallet'), ('rabbit', 'Rabbit LINE Pay'), ('scb_easy', 'SCB Easy'), ('cod', 'ชำระปลายทาง'), ('cash', 'เงินสด')], max_length=20, verbose_name='วิธีการชำระเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('preparing', 'จัดเตรียมสินค้า'), ('ready', 'พร้อมรับ/ส่ง'), ('delivering', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('delivery_address', models.TextField(blank=True, verbose_name='ที่อยู่จัดส่ง')),
                ('delivery_phone', models.CharField(blank=True, max_length=15, verbose_name='เบอร์โทรศัพท์สำหรับจัดส่ง')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='หมายเหตุการจัดส่ง')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวมสินค้า')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าจัดส่ง')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวมทั้งหมด')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาอัปเดต')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้า',
                'verbose_name_plural': 'รายการสินค้า',
            },
        ),
    ]
