# Generated by Django 4.2.25 on 2026-03-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='ชื่อร้าน/จุดอ้างอิง')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่ร้าน')),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='ละติจูดร้าน')),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='ลองจิจูดร้าน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุด')),
            ],
            options={
                'verbose_name': 'พิกัดร้าน',
                'verbose_name_plural': 'พิกัดร้าน',
            },
        ),
    ]
