# Generated by Django 4.2.25 on 2026-03-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_store_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='inventory_reserved',
            field=models.BooleanField(default=False, help_text='True เมื่อสร้างออเดอร์แล้วหักสต็อกในคลัง — ออเดอร์เก่าก่อนมีฟีเจอร์นี้จะเป็น False', verbose_name='หักสต็อกจากออเดอร์นี้แล้ว'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_restocked_on_cancel',
            field=models.BooleanField(default=False, help_text='กันคืนสต็อกซ้ำเมื่อยกเลิกออเดอร์', verbose_name='คืนสต็อกหลังยกเลิกแล้ว'),
        ),
    ]
