# Generated by Django 4.2.25 on 2025-10-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('line_pay', 'LINE Pay'), ('promptpay', 'PromptPay'), ('truemoney', 'TrueMoney Wallet'), ('rabbit', 'Rabbit LINE Pay'), ('scb_easy', 'SCB Easy'), ('cod', 'ชำระปลายทาง'), ('cash', 'เงินสด')], max_length=20, verbose_name='วิธีการชำระเงิน')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('processing', 'กำลังดำเนินการ'), ('completed', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('cancelled', 'ยกเลิก'), ('refunded', 'คืนเงิน')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code')),
                ('qr_image_url', models.URLField(blank=True, verbose_name='QR Image URL')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Bank Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาชำระเงิน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาอัปเดต')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'รายการชำระเงิน',
                'verbose_name_plural': 'รายการชำระเงิน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('promptpay', 'PromptPay'), ('line_pay', 'LINE Pay'), ('truemoney', 'TrueMoney'), ('rabbit', 'Rabbit LINE Pay'), ('scb_easy', 'SCB Easy')], max_length=20, verbose_name='ประเภท Webhook')),
                ('payload', models.JSONField(verbose_name='ข้อมูล Webhook')),
                ('signature', models.CharField(blank=True, max_length=500, verbose_name='Signature')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ยืนยันแล้ว')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาประมวลผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='payments.paymenttransaction', verbose_name='รายการชำระเงิน')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_method', models.CharField(max_length=50, verbose_name='วิธีการเช็ค')),
                ('check_result', models.JSONField(verbose_name='ผลการเช็ค')),
                ('status_before', models.CharField(max_length=20, verbose_name='สถานะก่อนเช็ค')),
                ('status_after', models.CharField(max_length=20, verbose_name='สถานะหลังเช็ค')),
                ('is_status_changed', models.BooleanField(default=False, verbose_name='สถานะเปลี่ยน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='payments.paymenttransaction', verbose_name='รายการชำระเงิน')),
            ],
            options={
                'verbose_name': 'บันทึกการเช็คสถานะ',
                'verbose_name_plural': 'บันทึกการเช็คสถานะ',
                'ordering': ['-created_at'],
            },
        ),
    ]
