# Generated by Django 4.2.25 on 2025-10-23 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='จำนวนสินค้าคงเหลือ')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมจำหน่าย')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='สินค้าโปรโมชั่น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
            },
        ),
    ]
