"""
Django settings for shop_delivery project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from urllib.parse import urlparse

from decouple import config
from django.core.exceptions import ImproperlyConfigured
import os

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# โหลด .env จากราก repo (shop-delivery/.env) หรือใต้ shop_delivery/.env — ให้ migrate จากเครื่องเห็น DATABASE_URL ได้โดยไม่พึ่ง cwd
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR.parent / '.env')
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass

def _optional_coord(name):
    """พิกัดร้าน — ใช้คำนวณระยะ Haversine เมื่อลูกค้าส่งพิกัดปลายทาง (ไม่ใช่ระยะถนน)"""
    raw = config(name, default='')
    if raw is None or str(raw).strip() == '':
        return None
    try:
        return float(raw)
    except (TypeError, ValueError):
        return None


def _comma_separated_list(name, default=''):
    """อ่านค่า comma-separated จาก env (เช่น origin สำหรับ CORS/CSRF)"""
    raw = config(name, default=default)
    if raw is None or str(raw).strip() == '':
        return []
    return [x.strip() for x in str(raw).split(',') if x.strip()]


DELIVERY_ORIGIN_LATITUDE = _optional_coord('DELIVERY_ORIGIN_LATITUDE')
DELIVERY_ORIGIN_LONGITUDE = _optional_coord('DELIVERY_ORIGIN_LONGITUDE')

# Load LINE config from env file
LINE_CONFIG_ENV = BASE_DIR / 'line_config.env'
if LINE_CONFIG_ENV.exists():
    from decouple import Config, RepositoryEnv
    env_config = Config(RepositoryEnv(LINE_CONFIG_ENV))
    # Override config with values from line_config.env
    os.environ.setdefault('LINE_CHANNEL_ACCESS_TOKEN', env_config.get('LINE_CHANNEL_ACCESS_TOKEN', ''))
    os.environ.setdefault('LINE_CHANNEL_SECRET', env_config.get('LINE_CHANNEL_SECRET', ''))
    os.environ.setdefault('LINE_LIFF_ID', env_config.get('LINE_LIFF_ID', ''))
    os.environ.setdefault('PROMPTPAY_NUMBER', env_config.get('PROMPTPAY_NUMBER', ''))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-dev-only-set-secret-key-in-env-for-shared-environments'
    else:
        raise ImproperlyConfigured(
            'Set SECRET_KEY in the environment when DEBUG=False (production).'
        )

# Render ตั้ง RENDER_EXTERNAL_HOSTNAME / RENDER_EXTERNAL_URL — ใส่ใน ALLOWED_HOSTS ให้ชัดเพื่อไม่ให้ DisallowedHost
_allowed_hosts_extra = _comma_separated_list('ALLOWED_HOSTS_EXTRA', default='')
_render_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if not _render_hostname:
    _render_url = os.environ.get('RENDER_EXTERNAL_URL', '').strip()
    if _render_url.startswith('http'):
        _render_hostname = urlparse(_render_url).hostname or ''
if _render_hostname and _render_hostname not in _allowed_hosts_extra:
    _allowed_hosts_extra.insert(0, _render_hostname)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'db3d99c5aa01.ngrok-free.app',
    '.ngrok-free.app',  # สำหรับ ngrok subdomain อื่นๆ
    '.ngrok.app',  # โดเมน ngrok รุ่นใหม่
    '.ngrok.io',
    '.onrender.com',  # subdomain *.onrender.com
] + _allowed_hosts_extra

# URL ของ SPA (Cloudflare Pages / dev) — ใช้ใน LOGIN_REDIRECT และ CORS
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.line',
    
    # Local apps
    'accounts',
    'products',
    'orders',
    'payments',
    'pdpa',
    'logistics',
    'line_bot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # อยู่สูงเพื่อจัดการ preflight ได้เร็ว
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'shop_delivery.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'shop_delivery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_URL = config('DATABASE_URL', default='')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'th'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
# ถ้าใช้ Render Persistent Disk ให้ mount แล้วตั้ง MEDIA_ROOT เป็น path เต็ม (ไฟล์จะไม่หายเมื่อ redeploy)
_media_root_override = config('MEDIA_ROOT', default='').strip()
if _media_root_override:
    MEDIA_ROOT = Path(_media_root_override).expanduser().resolve()
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework
REST_FRAMEWORK = {
    # Token ก่อน Session: SPA ส่ง Authorization + credentials ได้ session cookie ด้วย
    # ถ้า Session มาก่อน DRF จะ enforce CSRF บน POST/PATCH/DELETE แม้มี Token
    # ไม่ใช้ BasicAuthentication — ลดความเสี่ยง brute-force และไม่จำเป็นต่อ SPA/LIFF
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # เฟส B — endpoint ที่เปิดสาธารณะต้องใส่ AllowAny ในคลาส view โดยชัดเจน
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'shop_delivery.pagination.StandardPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# CORS settings - รองรับ credentials: 'include'
_cors_extra = _comma_separated_list('CORS_ALLOWED_ORIGINS_EXTRA', default='')
_fe = (FRONTEND_URL or '').strip()
if _fe.startswith('http'):
    _po = urlparse(_fe)
    if _po.scheme and _po.netloc:
        _origin = f'{_po.scheme}://{_po.netloc}'
        if _origin not in _cors_extra:
            _cors_extra.insert(0, _origin)

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://liff.line.me",
] + _cors_extra

# Allow dynamic ngrok / Cloudflare Pages preview URLs without editing env each deploy.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[a-zA-Z0-9.-]+\.ngrok-free\.app$",
    r"^http://[a-zA-Z0-9.-]+\.ngrok-free\.app$",
    r"^https://[a-zA-Z0-9.-]+\.ngrok\.app$",
    r"^http://[a-zA-Z0-9.-]+\.ngrok\.app$",
    r"^https://[a-zA-Z0-9.-]+\.ngrok\.io$",
    r"^http://[a-zA-Z0-9.-]+\.ngrok\.io$",
    r"^https://[a-zA-Z0-9.-]+\.pages\.dev$",
]

CORS_ALLOW_ALL_ORIGINS = False  # ต้องระบุ origin แบบเจาะจง
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'ngrok-skip-browser-warning',
]
# ตั้งค่า CORS preflight
CORS_PREFLIGHT_MAX_AGE = 86400

# Additional CORS settings

# LINE Messaging API Channel (สำหรับ LINE Bot) — ห้ามใส่ความลับจริงใน repo; ตั้งใน .env
LINE_CHANNEL_ACCESS_TOKEN = config('LINE_CHANNEL_ACCESS_TOKEN', default='')
LINE_CHANNEL_SECRET = config('LINE_CHANNEL_SECRET', default='')

# LINE Login Channel (สำหรับ LIFF)
LINE_LOGIN_CHANNEL_ID = config('LINE_LOGIN_CHANNEL_ID', default='')
LINE_LOGIN_CHANNEL_SECRET = config('LINE_LOGIN_CHANNEL_SECRET', default='')
LINE_LIFF_ID = config('LINE_LIFF_ID', default='')
# path หลัง LIFF ID สำหรับดีลิงก์แจ้งเตือนออเดอร์ — ต่อท้าย Endpoint URL ใน LINE Console
# default: orders/<id> เมื่อ Endpoint ลงท้ายด้วย .../customer/ ได้ URL สุดท้าย .../customer/orders/<id>
# ถ้า Endpoint เป็นโดเมนราก (ไม่มี /customer) ให้ตั้งเป็น customer/orders
LINE_LIFF_ORDER_URI_PREFIX = (os.getenv('LINE_LIFF_ORDER_URI_PREFIX', 'orders') or 'orders').strip().strip('/')

# Payment Gateway settings (ค่าจริงจาก env เท่านั้น)
PROMPTPAY_MERCHANT_ID = config('PROMPTPAY_MERCHANT_ID', default='')
PROMPTPAY_API_KEY = config('PROMPTPAY_API_KEY', default='')
PROMPTPAY_NUMBER = config('PROMPTPAY_NUMBER', default='')
# ใช้ยืนยัน POST /api/payments/webhook/ — ส่ง header X-Payment-Webhook-Secret ให้ตรงค่านี้ (production บังคับถ้า DEBUG=False)
PAYMENT_WEBHOOK_SECRET = config('PAYMENT_WEBHOOK_SECRET', default='')

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Django Allauth settings
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_EMAIL_REQUIRED = False

# Redirect after social login (FRONTEND_URL นิยามด้านบน)
LOGIN_REDIRECT_URL = f"{FRONTEND_URL.rstrip('/')}/"  # Redirect กลับไปหน้าแรกของ frontend
SOCIALACCOUNT_LOGIN_ON_GET = True  # โดยpass confirmation page
SOCIALACCOUNT_AUTO_SIGNUP = True  # สร้าง user อัตโนมัติ
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'  # Custom adapter

# LINE Provider settings
# Note: SocialApp ถูกจัดการผ่าน Django Admin
# ไม่ต้องกำหนด APP ที่นี่ เพราะจะทำให้ MultipleObjectsReturned
SOCIALACCOUNT_PROVIDERS = {
    'line': {
        'SCOPE': ['profile', 'openid', 'email'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': False,
    }
}

# CSRF settings for allauth + SPA ที่ยิงมาที่ API คนละ origin (localhost ↔ ngrok / Pages / Render)
_csrf_extra = _comma_separated_list('CSRF_TRUSTED_ORIGINS_EXTRA', default='')
_render_ext = os.environ.get('RENDER_EXTERNAL_URL', '').strip().rstrip('/')
if _render_ext.startswith('http') and _render_ext not in _csrf_extra:
    _csrf_extra.append(_render_ext)
_fe_csrf = (FRONTEND_URL or '').strip()
if _fe_csrf.startswith('http'):
    _fcp = urlparse(_fe_csrf)
    if _fcp.scheme and _fcp.netloc:
        _fe_origin = f'{_fcp.scheme}://{_fcp.netloc}'
        if _fe_origin not in _csrf_extra:
            _csrf_extra.insert(0, _fe_origin)

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://*.ngrok-free.app',
    'http://*.ngrok-free.app',
    'https://*.ngrok.app',
    'http://*.ngrok.app',
    'https://*.ngrok.io',
    'http://*.ngrok.io',
    'https://liff.line.me',
] + _csrf_extra

# Security settings for ngrok HTTPS
# ถ้า frontend อยู่คนละ site กับ API (เช่น http://localhost:3000 → https://xxx.ngrok-free.app)
# และต้องการให้ browser ส่ง session/csrf cookie ไปกับ fetch(..., credentials: 'include')
# ให้ตั้ง NGROK_CROSS_SITE_COOKIES=True (ใช้กับ HTTPS เท่านั้น)
_NGROK_CROSS_SITE = config('NGROK_CROSS_SITE_COOKIES', default=False, cast=bool)
CSRF_COOKIE_SECURE = _NGROK_CROSS_SITE
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'None' if _NGROK_CROSS_SITE else 'Lax'
SESSION_COOKIE_SECURE = _NGROK_CROSS_SITE
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'None' if _NGROK_CROSS_SITE else 'Lax'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # สำหรับ ngrok

# Logging — production / Docker ใช้ stdout (Render / Gunicorn)
if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'file': {
                'level': 'INFO',
                'class': 'logging.FileHandler',
                'filename': BASE_DIR / 'logs' / 'django.log',
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'level': 'INFO',
                'propagate': True,
            },
        },
    }
else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
            },
        },
        'root': {'handlers': ['console'], 'level': 'INFO'},
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': 'INFO',
                'propagate': False,
            },
        },
    }
