# Generated by Django 4.2.25 on 2025-10-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=100, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='ชื่อแสดงใน LINE')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='URL รูปโปรไฟล์')),
                ('status_message', models.CharField(blank=True, max_length=200, verbose_name='สถานะ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LINE Bot User',
                'verbose_name_plural': 'LINE Bot Users',
            },
        ),
        migrations.CreateModel(
            name='LineNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'สร้างคำสั่งซื้อ'), ('order_preparing', 'จัดเตรียมสินค้า'), ('order_ready', 'พร้อมรับ/ส่ง'), ('order_delivering', 'กำลังจัดส่ง'), ('order_delivered', 'จัดส่งสำเร็จ'), ('order_cancelled', 'ยกเลิกคำสั่งซื้อ'), ('payment_success', 'ชำระเงินสำเร็จ'), ('payment_failed', 'ชำระเงินล้มเหลว'), ('delivery_assigned', 'มอบหมายงานจัดส่ง'), ('delivery_picked_up', 'รับสินค้าแล้ว'), ('delivery_delivered', 'จัดส่งสำเร็จ')], max_length=30, verbose_name='ประเภทการแจ้งเตือน')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ส่งสำเร็จ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาส่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='คำสั่งซื้อ')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot.linebotuser', verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'LINE Notification',
                'verbose_name_plural': 'LINE Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'ข้อความ'), ('image', 'รูปภาพ'), ('template', 'Template'), ('flex', 'Flex Message')], max_length=20, verbose_name='ประเภทข้อความ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ส่งสำเร็จ')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาส่ง')),
                ('error_message', models.TextField(blank=True, verbose_name='ข้อความผิดพลาด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='line_bot.linebotuser', verbose_name='ผู้รับ')),
            ],
            options={
                'verbose_name': 'LINE Message',
                'verbose_name_plural': 'LINE Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
