# Generated by Django 4.2.25 on 2025-10-23 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(max_length=13, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('date_of_birth', models.DateField(verbose_name='วันเดือนปีเกิด')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
            },
        ),
        migrations.CreateModel(
            name='DataProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('order_processing', 'การประมวลผลคำสั่งซื้อ'), ('delivery', 'การจัดส่ง'), ('customer_service', 'การบริการลูกค้า'), ('marketing', 'การตลาด'), ('analytics', 'การวิเคราะห์')], max_length=30, verbose_name='วัตถุประสงค์')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('data_categories', models.TextField(verbose_name='หมวดหมู่ข้อมูล')),
                ('legal_basis', models.TextField(verbose_name='ฐานกฎหมาย')),
                ('retention_period', models.CharField(max_length=100, verbose_name='ระยะเวลาการเก็บรักษา')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'กิจกรรมการประมวลผลข้อมูล',
                'verbose_name_plural': 'กิจกรรมการประมวลผลข้อมูล',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('pickup', 'รับเองที่ร้าน'), ('delivery', 'จัดส่ง')], max_length=10, verbose_name='ประเภทคำสั่งซื้อ')),
                ('payment_method', models.CharField(choices=[('line_pay', 'LINE Pay'), ('promptpay', 'PromptPay'), ('truemoney', 'TrueMoney Wallet'), ('rabbit', 'Rabbit LINE Pay'), ('scb_easy', 'SCB Easy'), ('cod', 'ชำระปลายทาง'), ('cash', 'เงินสด')], max_length=10, verbose_name='วิธีการชำระเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('preparing', 'จัดเตรียมสินค้า'), ('ready', 'พร้อมรับ/ส่ง'), ('delivering', 'กำลังจัดส่ง'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('delivery_address', models.TextField(blank=True, verbose_name='ที่อยู่จัดส่ง')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าจัดส่ง')),
                ('delivery_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ระยะทาง (กม.)')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลารับสินค้า')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวมสินค้า')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวมทั้งหมด')),
                ('cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='จำนวนเงินสด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('line_pay', 'LINE Pay'), ('promptpay', 'PromptPay'), ('truemoney', 'TrueMoney Wallet'), ('rabbit', 'Rabbit LINE Pay'), ('scb_easy', 'SCB Easy'), ('cod', 'ชำระปลายทาง'), ('cash', 'เงินสด')], max_length=20, verbose_name='วิธีการชำระเงิน')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='จำนวนเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('processing', 'กำลังดำเนินการ'), ('completed', 'สำเร็จ'), ('failed', 'ล้มเหลว'), ('cancelled', 'ยกเลิก'), ('refunded', 'คืนเงิน')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code')),
                ('qr_image_url', models.URLField(blank=True, verbose_name='QR Image URL')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Transaction ID')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='Reference ID')),
                ('bank_reference', models.CharField(blank=True, max_length=100, verbose_name='Bank Reference')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาชำระเงิน')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='เวลาอัปเดต')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='delivery.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'รายการชำระเงิน',
                'verbose_name_plural': 'รายการชำระเงิน',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='เวอร์ชัน')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('effective_date', models.DateField(verbose_name='วันที่มีผลบังคับใช้')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'นโยบายความเป็นส่วนตัว',
                'verbose_name_plural': 'นโยบายความเป็นส่วนตัว',
            },
        ),
        migrations.CreateModel(
            name='ServiceHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('delivery', 'บริการจัดส่ง'), ('pickup', 'บริการรับเองที่ร้าน')], max_length=10, verbose_name='ประเภทบริการ')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
            ],
            options={
                'verbose_name': 'เวลาบริการ',
                'verbose_name_plural': 'เวลาบริการ',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'ลูกค้า'), ('store_admin', 'แอดมินร้านค้า'), ('driver', 'คนขับรถส่ง'), ('super_admin', 'ผู้ดูแลระบบ')], max_length=20, verbose_name='บทบาท')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'บทบาทผู้ใช้งาน',
                'verbose_name_plural': 'บทบาทผู้ใช้งาน',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='รูปภาพ')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='จำนวนสินค้าคงเหลือ')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมจำหน่าย')),
                ('is_special_offer', models.BooleanField(default=False, verbose_name='สินค้าโปรโมชั่น')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='delivery.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้า',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_type', models.CharField(choices=[('promptpay', 'PromptPay'), ('line_pay', 'LINE Pay'), ('truemoney', 'TrueMoney'), ('rabbit', 'Rabbit LINE Pay'), ('scb_easy', 'SCB Easy')], max_length=20, verbose_name='ประเภท Webhook')),
                ('payload', models.JSONField(verbose_name='ข้อมูล Webhook')),
                ('signature', models.CharField(blank=True, max_length=500, verbose_name='Signature')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ยืนยันแล้ว')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาประมวลผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='delivery.paymenttransaction', verbose_name='รายการชำระเงิน')),
            ],
            options={
                'verbose_name': 'Payment Webhook',
                'verbose_name_plural': 'Payment Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_method', models.CharField(max_length=50, verbose_name='วิธีการเช็ค')),
                ('check_result', models.JSONField(verbose_name='ผลการเช็ค')),
                ('status_before', models.CharField(max_length=20, verbose_name='สถานะก่อนเช็ค')),
                ('status_after', models.CharField(max_length=20, verbose_name='สถานะหลังเช็ค')),
                ('is_status_changed', models.BooleanField(default=False, verbose_name='สถานะเปลี่ยน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาสร้าง')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='delivery.paymenttransaction', verbose_name='รายการชำระเงิน')),
            ],
            options={
                'verbose_name': 'บันทึกการเช็คสถานะ',
                'verbose_name_plural': 'บันทึกการเช็คสถานะ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้า',
                'verbose_name_plural': 'รายการสินค้า',
            },
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=100, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='ชื่อแสดงใน LINE')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='URL รูปโปรไฟล์')),
                ('status_message', models.CharField(blank=True, max_length=200, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LINE User',
                'verbose_name_plural': 'LINE Users',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, verbose_name='เลขใบขับขี่')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='ประเภทรถ')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='เลขทะเบียนรถ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมรับงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลคนขับรถส่ง',
                'verbose_name_plural': 'ข้อมูลคนขับรถส่ง',
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลามอบหมาย')),
                ('status', models.CharField(choices=[('assigned', 'ได้รับมอบหมาย'), ('accepted', 'รับงาน'), ('picked_up', 'รับสินค้าแล้ว'), ('delivered', 'จัดส่งสำเร็จ'), ('cancelled', 'ยกเลิก')], default='assigned', max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='คนขับ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='delivery.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'การมอบหมายงานจัดส่ง',
                'verbose_name_plural': 'การมอบหมายงานจัดส่ง',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_delivery_time', models.DateTimeField(verbose_name='เวลาจัดส่งโดยประมาณ')),
                ('actual_delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาจัดส่งจริง')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='คนส่ง')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='delivery.order', verbose_name='คำสั่งซื้อ')),
            ],
            options={
                'verbose_name': 'การจัดส่ง',
                'verbose_name_plural': 'การจัดส่ง',
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('marketing', 'การตลาด'), ('data_processing', 'การประมวลผลข้อมูล'), ('third_party', 'การแชร์ข้อมูลกับบุคคลที่สาม'), ('analytics', 'การวิเคราะห์ข้อมูล')], max_length=20, verbose_name='ประเภทความยินยอม')),
                ('is_given', models.BooleanField(verbose_name='ให้ความยินยอม')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่ให้ความยินยอม')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ถอนความยินยอม')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='delivery.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'บันทึกความยินยอม',
                'verbose_name_plural': 'บันทึกความยินยอม',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'สร้าง'), ('read', 'อ่าน'), ('update', 'แก้ไข'), ('delete', 'ลบ'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ')], max_length=10, verbose_name='การกระทำ')),
                ('model_name', models.CharField(max_length=100, verbose_name='ชื่อ Model')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID วัตถุ')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'บันทึกการเข้าถึง',
                'verbose_name_plural': 'บันทึกการเข้าถึง',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, verbose_name='รหัสพนักงาน')),
                ('department', models.CharField(max_length=100, verbose_name='แผนก')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลแอดมินร้านค้า',
                'verbose_name_plural': 'ข้อมูลแอดมินร้านค้า',
            },
        ),
    ]
