# Generated by Django 4.2.25 on 2025-10-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'ลูกค้า'), ('store_admin', 'แอดมินร้านค้า'), ('driver', 'คนขับรถส่ง'), ('super_admin', 'ผู้ดูแลระบบ')], max_length=20, verbose_name='บทบาท')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'บทบาทผู้ใช้งาน',
                'verbose_name_plural': 'บทบาทผู้ใช้งาน',
            },
        ),
        migrations.CreateModel(
            name='LineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=100, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='ชื่อแสดงใน LINE')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='URL รูปโปรไฟล์')),
                ('status_message', models.CharField(blank=True, max_length=200, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LINE User',
                'verbose_name_plural': 'LINE Users',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, verbose_name='เลขใบขับขี่')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='ประเภทรถ')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='เลขทะเบียนรถ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('is_available', models.BooleanField(default=True, verbose_name='พร้อมรับงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลคนขับรถส่ง',
                'verbose_name_plural': 'ข้อมูลคนขับรถส่ง',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(max_length=13, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('date_of_birth', models.DateField(verbose_name='วันเดือนปีเกิด')),
                ('address', models.TextField(verbose_name='ที่อยู่')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, verbose_name='รหัสพนักงาน')),
                ('department', models.CharField(max_length=100, verbose_name='แผนก')),
                ('phone_number', models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ข้อมูลแอดมินร้านค้า',
                'verbose_name_plural': 'ข้อมูลแอดมินร้านค้า',
            },
        ),
    ]
