# Generated by Django 4.2.25 on 2026-03-21 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_expand_coordinate_precision_again'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('admin_login', 'เข้าสู่ระบบแอดมิน'), ('admin_logout', 'ออกจากระบบแอดมิน'), ('product_create', 'เพิ่มสินค้า'), ('product_update', 'แก้ไขสินค้า'), ('product_delete', 'ลบสินค้า'), ('category_create', 'เพิ่มหมวดหมู่'), ('category_update', 'แก้ไขหมวดหมู่'), ('category_delete', 'ลบหมวดหมู่'), ('order_status', 'เปลี่ยนสถานะคำสั่งซื้อ'), ('payment_slip_review', 'ตรวจสอบสลิปโอนเงิน'), ('assign_driver', 'มอบหมายคนขับ'), ('staff_create', 'เพิ่มบัญชีพนักงาน'), ('staff_update', 'แก้ไขบัญชีพนักงาน'), ('staff_delete', 'ลบบัญชีพนักงาน')], max_length=40, verbose_name='ประเภท')),
                ('target_type', models.CharField(blank=True, max_length=40, verbose_name='ประเภทเป้าหมาย')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='รหัสเป้าหมาย')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='สรุป')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='รายละเอียด')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='เวลา')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทำรายการ')),
            ],
            options={
                'verbose_name': 'ประวัติพนักงาน',
                'verbose_name_plural': 'ประวัติพนักงาน',
                'ordering': ['-created_at'],
            },
        ),
    ]
