# Generated by Django 4.2.25 on 2025-10-23 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('order_processing', 'การประมวลผลคำสั่งซื้อ'), ('delivery', 'การจัดส่ง'), ('customer_service', 'การบริการลูกค้า'), ('marketing', 'การตลาด'), ('analytics', 'การวิเคราะห์')], max_length=30, verbose_name='วัตถุประสงค์')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('data_categories', models.TextField(verbose_name='หมวดหมู่ข้อมูล')),
                ('legal_basis', models.TextField(verbose_name='ฐานกฎหมาย')),
                ('retention_period', models.CharField(max_length=100, verbose_name='ระยะเวลาการเก็บรักษา')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'กิจกรรมการประมวลผลข้อมูล',
                'verbose_name_plural': 'กิจกรรมการประมวลผลข้อมูล',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='เวอร์ชัน')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('effective_date', models.DateField(verbose_name='วันที่มีผลบังคับใช้')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'นโยบายความเป็นส่วนตัว',
                'verbose_name_plural': 'นโยบายความเป็นส่วนตัว',
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('marketing', 'การตลาด'), ('data_processing', 'การประมวลผลข้อมูล'), ('third_party', 'การแชร์ข้อมูลกับบุคคลที่สาม'), ('analytics', 'การวิเคราะห์ข้อมูล')], max_length=20, verbose_name='ประเภทความยินยอม')),
                ('is_given', models.BooleanField(verbose_name='ให้ความยินยอม')),
                ('given_at', models.DateTimeField(auto_now_add=True, verbose_name='เวลาที่ให้ความยินยอม')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ถอนความยินยอม')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='accounts.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'บันทึกความยินยอม',
                'verbose_name_plural': 'บันทึกความยินยอม',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'สร้าง'), ('read', 'อ่าน'), ('update', 'แก้ไข'), ('delete', 'ลบ'), ('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ')], max_length=10, verbose_name='การกระทำ')),
                ('model_name', models.CharField(max_length=100, verbose_name='ชื่อ Model')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID วัตถุ')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='เวลา')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'บันทึกการเข้าถึง',
                'verbose_name_plural': 'บันทึกการเข้าถึง',
                'ordering': ['-timestamp'],
            },
        ),
    ]
